CREATE TABLE KARTEIKASTEN (
  LETTER            	VARCHAR(5),
  TITLE            	VARCHAR(200),
  TEXT            	VARCHAR(200),
  DB            	VARCHAR(50),
  RATING            INT,
  ENTRY_GROUP       VARCHAR(200),
  PRIMARY KEY (TITLE)
  ) DEFAULT CHARACTER SET=utf8;